REWARD_FUNCTIONS = "GOAT"
TIMESTEPS = 1_000_000
GIVE_TILE_VISITED_REWARD = True
L2D_HARD_BARRIER = False
L2D_DISABLE_SIDE_RAYS = True

MAX_EPISODE_REWARD = 1000.0
MAX_EPISODE_STEPS = 1500

L2D_TIME_PENALTY = 0.05 # Constant penalty per step (time cost)
L2D_CENTER_REWARD_WEIGHT = 1 # Centering reward weight
L2D_OFF_TRACK_PENALTY = 2 # Penalty for going off track


L2D_GRASS_TIMEOUT = 0.5  # seconds
L2D_GRASS_TIMEOUT_PENALTY = 500 # Penalty for going off track

