REWARD_FUNCTIONS = "7"
TIMESTEPS = 1_000_000
GIVE_TILE_VISITED_REWARD = True

MAX_EPISODE_REWARD = 1000.0
MAX_EPISODE_STEPS = 1500

FAULT_LOCATION = -1 # FRONT_LEFT : 0, FRONT_RIGHT : 1, BACK_LEFT : 2, BACK_RIGHT : 3, RANDOM : -1
FAULT_PROBABILITY = 0
FAULT_DURATION = 1000 #1e5
FAULT_TYPE = "TORQUE_REDUCTION" #"LOCK"
FAULT_STEP_RANGE = (200, 300)

L2D_TIME_PENALTY = 0.05 # Constant penalty per step (time cost)
L2D_CENTER_REWARD_WEIGHT = 1 # Centering reward weight
L2D_SPEED_REWARD_WEIGHT = 0.1
L2D_ALIGNMENT_ZONE_RATIO = 0.5 # Zone within which alignment is "perfect"

L2D_OFF_TRACK_PENALTY = 1 # Penalty for going off track

L2D_HARD_BARRIER = False
L2D_GRASS_TIMEOUT = 0.5  # seconds
L2D_GRASS_TIMEOUT_PENALTY = 500 # Penalty for going off track

L2D_STEER_RATE = 1 # radians per second steering change

L2D_DISABLE_SIDE_RAYS = True